### ISSUE TITLE
Registration - remove the sil.org email in the archive

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#60]
For SPadv, I think we should remove the auto-default sil.org email that is in the Archive drawer.  
The auto-default emails in the Archive drawer are there so that when Registration info is sent it will automatically be sent (also) to this email for the purpose of analytics -- so a database of registered users (translators, trainers, checkers) can be built.  Since forking from SIL and the SP app and rebranding as SPadv, perhaps we should not assume that SIL desires to get this Registration info for software that they do not own.

**Comment by techteam25** [comment]
What email should things be sent to instead?

**Comment by RobinRempel** [comment]
For now, we can leave that field blank.  The Registration is already
automatically going to ***@***.***

**Comment by RobinRempel** [comment]
I am not seeing that this issue has been addressed in the SPadv 1.1.2 debugging build. I think (?) this can be easily done by deleting the sil.org email from the strings file.

**Comment by techteam25** [comment]
Well, we took that email address out of the only place in the entire project where that it existed... the strings file.   And it still gets into the email?!?  We'll track it down somehow.

**Comment by techteam25** [comment]
This issue is in the registration file in the SPworkspace folder.  After the registration is first done the email address resides in the registration file.  You can edit the file or remove it and redo the registration.

@RobinRempel

**Comment by techteam25** [comment]
The change needs to be when going into "Update Registration" in the app, 
if any email address is SPadv_info@sil.org then clear it out!

**Comment by techteam25** [comment]
Robin, would you like to have the app automatically remove the spadv_info@sil.org email address from the saved registration file upon the user going back into "Update Registration"?  We should be able to remove it before it is displayed, and that was remove it from existing phones like yours.  This would remove it from everyone who ever installs the app, even SIL people.

Another option is to change the field in registration where that is saved so the user can edit it, that way you can remove it or tell a existing users to remove it.

@RobinRempel

**Comment by RobinRempel** [comment]
The SPadv app should not have any @sil.org email address in the archives.
(The email you listed spadv_info@sil.org is nonexistent.  I think it is SPapp_info@sil.org)
I don't think it is necessary to remove the @sil.org email from pre-existing registrations.  
Let's leave the default emails in the Archive as they are.  Emails can be manually inserted or removed in the email application before sending.

**Comment by RobinRempel** [comment]
This issue has been dealt with.  Closing.
